//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace HvisaoApp.Models
{
    using System.Collections.Generic;

    public partial class Estacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estacao()
        {
            this.Impressora = new HashSet<Impressora>();
        }

        [Key]
        public int EstacaoId { get; set; }
        [Display(Name = "Hostname")]
        [Required(ErrorMessage = "Informe o nome da máquina.")]
        public string Hostname { get; set; }
        [Display(Name = "Setor")]
        [Required(ErrorMessage = "Informe o setor.")]
        public string Setor { get; set; }
        [Display(Name = "Endereço IP")]
        [Required(ErrorMessage = "Informe o endereço IP.")]
        public string EnderecoIp { get; set; }
        [Display(Name = "Sistema Operacional")]
        [Required(ErrorMessage = "Informe o Sistema Operacional.")]
        public string SistemaOperacional { get; set; }
        [Display(Name = "Chave de Ativação")]
        [Required(ErrorMessage = "Informe a chave de ativação.")]
        public string ChavedeAtivacao { get; set; }
        [Display(Name = "Ativo?")]
        public bool Ativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Impressora> Impressora { get; set; }
    }
}
