//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HvisaoApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestorAtivosEntities : DbContext
    {
        public GestorAtivosEntities()
            : base("name=GestorAtivosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Estacao> Estacao { get; set; }
        public virtual DbSet<Impressora> Impressora { get; set; }
        public virtual DbSet<Servidor> Servidor { get; set; }
    }
}
