//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace HvisaoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Impressora
    {
        [Key]
        public int ImpressoraId { get; set; }
        [Display(Name = "Marca")]
        [Required(ErrorMessage = "Informe a marca.")]
        public string Marca { get; set; }
        [Display(Name = "Modelo")]
        [Required(ErrorMessage = "Informe o modelo da impressora.")]
        public string Modelo { get; set; }
        [Display(Name = "Monocromática")]
        public bool Monocromatica { get; set; }
        [Display(Name = "Colorida")]
        public bool Colorida { get; set; }
        [Display(Name = "Nome")]
        [Required(ErrorMessage = "Informe o nome da impressora.")]
        public string Nome { get; set; }
        [Display(Name = "Setor")]
        [Required(ErrorMessage = "Informe o setor.")]
        public string Setor { get; set; }
        [Display(Name = "Endereço IP")]
        [Required(ErrorMessage = "Informe o endereço IP.")]
        public string EnderecoIp { get; set; }
        [Required(ErrorMessage = "Informe a estação pertencente.")]
        public int EstacaoId { get; set; }
        [Display(Name = "Ativo?")]
        public bool Ativo { get; set; }
    
        public virtual Estacao Estacao { get; set; }
    }
}
