//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace HvisaoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servidor
    {
        [Key]
        public int ServidorId { get; set; }
        [Display(Name = "Hostname")]
        [Required(ErrorMessage = "Informe o hostname.")]
        public string Hostname { get; set; }
        [Display(Name = "Função")]
        [Required(ErrorMessage = "Informe a função do servidor.")]
        public string Funcao { get; set; }
        [Display(Name = "Endereço IP")]
        [Required(ErrorMessage = "Informe o endereço IP.")]
        public string EnderecoIp { get; set; }
        [Display(Name = "Sistema Operacional")]
        [Required(ErrorMessage = "Informe o Sistema Operacional.")]
        public string SistemaOperacional { get; set; }
        [Display(Name = "Chave de Ativação")]
        [Required(ErrorMessage = "Informe a chave de ativação.")]
        public string ChavedeAtivacao { get; set; }
    }
}
